### PR TITLE
pre-commit: Add support for typescript hook

### PR DESCRIPTION
**Pull request by Holzhaus**
Can you test this?

I have never used typescript. How can I lint a controllerscript? This does not print any warnings:

    $ tsc --noEmit --allowJs res/controller/SomeController.js

### CODE REVIEW

**Comment by Swiftb0y** [comment]
We need to use `--checkJs` as well but it's more complicated than that. I am unable instruct tsc to acknowledge the definition file as well. I'll look into it again but tsc is really picky and assumes the presence of a regular typescript project folder structure. So in case I find a solution, it's more a hack than a solution.

**Comment by Swiftb0y** [comment]
It should now be possible to lint using `tsc --noEmit --allowJs --checkJS --typeRoots res/controllers/typings res/controller/SomeController.js`

**Comment by Holzhaus** [comment]
> It should now be possible to lint using `tsc --noEmit --allowJs --checkJS --typeRoots res/controllers/typings res/controller/SomeController.js`
> 
> Once we migrate to ES7, we'd also have to specify `--lib es7`.

I tried this, but now I get:
```
 res/controllers/Roland_DJ-505-scripts.js:1744:47 - error TS2304: Cannot find name 'components'.
10063
10064 1744 DJ505.PitchPlayMode.prototype = Object.create(components.ComponentContainer.prototype);
10065                                                    ~~~~~~~~~~
```

**Comment by Swiftb0y** [comment]
That is to be expected. I still need to write JsDoc annotations (and transpile them into ambient declarations) for the componentsJS, common-controller-scripts.js etc.

**Comment by Holzhaus** [comment]
Ok. The type checks work so far:

```
res/controllers/Roland_DJ-505-scripts.js:1022:35 - error TS2345: Argument of type '"yikes!"' is not assignable to parameter of type 'number'.

1022 DJ505.PadColorMap.getNearestColor("yikes!");
                                       ~~~~~~~~
```

What happens if I inherit from a components class in a controller script? I don't have to write a `*.ts` file, right?

```
res/controllers/Roland_DJ-505-scripts.js:726:50 - error TS2304: Cannot find name 'components'.

726 DJ505.DeckToggleButton.prototype = Object.create(components.Button.prototype);
                                                     ~~~~~~~~~~

res/controllers/Roland_DJ-505-scripts.js:728:14 - error TS2339: Property 'isPress' does not exist on type 'DeckToggleButton'.

728     if (this.isPress(channel, control, value, status)) {
                 ~~~~~~~
```

**Comment by Swiftb0y** [comment]
Inheritance should work just fine. The primary issue is the way we "load modules". If we were to use regular ES6 imports, typescript would recognize the types just fine. Actually, I'd be interesting to see what happens when you use `/// reference="midi- components.js"`. Does tsc at least acknowledge the `components` namespace?

**Comment by Holzhaus** [comment]
I think this is not relevant anymore, right?

**Comment by Swiftb0y** [comment]
Not really. I do plan to revisit this some time, but I'm currently otherwise occupied.

**Pull request closed without merging**
